apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ikno-web
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/charemma/ikno-web
    newName: ghcr.io/charemma/ikno-web
    newTag: latest
